language: python
python:
  - "3.4"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y expect
script:
  - mv credentials.EXAMPLE.py credentials.py
  - sed -ri "s/YOUR_TOKEN_HERE/$HANABI_SERVER_TOKEN/" credentials.py
  - sed -ri "s/YOUR_TAG_HERE/$HANABI_SERVER_TAG/" credentials.py
  - python -m unittest discover
  - flake8 --max-line-length=100 --ignore E221,E127,E241
  - expect test.exp
after_success:
  - "curl -H \"Content-Type: application/json\" --data '{\"build\": true}' -X POST \"https://registry.hub.docker.com/u/jamespstrachan/hanabi/trigger/$DOCKER_BUILD_TOKEN/\""